Error running function f attempt to compare nil with number
Error running function f attempt to compare nil with number
Error running function f attempt to compare nil with number
Error running function f attempt to compare nil with number
srun: error: i01r01c01s05: task 1: Aborted (core dumped)
srun: launch/slurm: _step_signal: Terminating StepId=3460174.0
srun: error: i01r01c03s03: task 7: Aborted (core dumped)
slurmstepd: error: *** STEP 3460174.0 ON i01r01c01s02 CANCELLED AT 2024-07-24T22:29:33 ***
srun: error: i01r01c01s08: task 3: Aborted (core dumped)
srun: error: i01r01c01s11: task 6: Aborted (core dumped)
srun: error: i01r01c01s10: task 5: Terminated
srun: error: i01r01c03s05: task 9: Terminated
srun: error: i01r01c03s04: task 8: Terminated
srun: error: i01r01c03s06: task 10: Terminated
srun: error: i01r01c03s11: task 15: Terminated
srun: error: i01r01c03s07: task 11: Terminated
srun: error: i01r01c03s09: task 13: Terminated
srun: error: i01r01c03s08: task 12: Terminated
srun: error: i01r01c03s10: task 14: Terminated
srun: error: i01r01c01s07: task 2: Terminated
srun: error: i01r01c01s09: task 4: Terminated
srun: error: i01r01c01s02: task 0: Terminated
srun: Force Terminated StepId=3460174.0
/var/spool/slurm/job3460174/slurm_script: line 66: pushd: /hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/outputs_tmp: No such file or directory
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/.local/bin/seissol_output_extractor", line 8, in <module>
    sys.exit(main())
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmfwriter/seissol_output_extractor.py", line 143, in main
    sx = SeissolxdmfExtended(args.xdmfFilename)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmf/seissolxdmf.py", line 14, in __init__
    with open (xdmfFilename, "r") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'output-fault.xdmf'
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/.local/bin/seissol_output_extractor", line 8, in <module>
    sys.exit(main())
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmfwriter/seissol_output_extractor.py", line 143, in main
    sx = SeissolxdmfExtended(args.xdmfFilename)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmf/seissolxdmf.py", line 14, in __init__
    with open (xdmfFilename, "r") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'output-surface.xdmf'
/var/spool/slurm/job3460174/slurm_script: line 72: popd: directory stack empty
mv: cannot stat '/hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/outputs_tmp': No such file or directory
cp: cannot create directory '/hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs/regional-only/jobid_3460174/logs': No such file or directory
