Fri Jul 19 00:46:26, Warn:  Output directory does not exist yet. We therefore create it now. 
/var/spool/slurm/job3453792/slurm_script: line 66: pushd: /hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs-general/outputs_tmp: No such file or directory
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/.local/bin/seissol_output_extractor", line 8, in <module>
    sys.exit(main())
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmfwriter/seissol_output_extractor.py", line 143, in main
    sx = SeissolxdmfExtended(args.xdmfFilename)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmf/seissolxdmf.py", line 14, in __init__
    with open (xdmfFilename, "r") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'output-fault.xdmf'
Traceback (most recent call last):
  File "/dss/dsshome1/01/di35poq/.local/bin/seissol_output_extractor", line 8, in <module>
    sys.exit(main())
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmfwriter/seissol_output_extractor.py", line 143, in main
    sx = SeissolxdmfExtended(args.xdmfFilename)
  File "/dss/dsshome1/01/di35poq/.local/lib/python3.8/site-packages/seissolxdmf/seissolxdmf.py", line 14, in __init__
    with open (xdmfFilename, "r") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'output-surface.xdmf'
/var/spool/slurm/job3453792/slurm_script: line 72: popd: directory stack empty
mv: cannot stat '/hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs-general/outputs_tmp': No such file or directory
cp: cannot create directory '/hppfs/scratch/01/di35poq/haiti-rupture-outputs/dynamic-rupture-outputs-general/regional-only/jobid_3453792/logs': No such file or directory
